import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#E1DED3',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    paddingTop: 80,
  },
  hero: {
    alignItems: 'center',
    marginTop: 40,
  },
  logo: {
    marginBottom: 28,
  },
  heading: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 44,
    color: '#2F2E2C',
    textAlign: 'center',
    marginBottom: 18,
  },
  subheading: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 19,
    lineHeight: 28,
    color: '#5A5546',
    textAlign: 'center',
  },
  actions: {
    width: '80%',
    alignItems: 'center',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#816148',
    borderRadius: 999,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonPressed: {
    opacity: 0.85,
  },
  primaryButtonDisabled: {
    backgroundColor: '#B7AE9B',
    opacity: 0.6,
  },
  primaryButtonText: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 17,
    color: '#E1DED3',
  },
  resendButton: {
    marginTop: 16,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resendButtonPressed: {
    opacity: 0.6,
  },
  resendButtonText: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 14,
    color: '#5A5546',
    paddingBottom: 20
  },
  scheduleTop: {
    width: '100%',
  },
  progressTrack: {
    flexDirection: 'row',
    width: '100%',
    height: 4,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#D6D0C0',
    marginBottom: 32,
  },
  progressFill: {
    width: '55%',
    backgroundColor: '#2F2E2C',
    borderRadius: 999,
  },
  scheduleHeading: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 28,
    color: '#2F2E2C',
    textAlign: 'left',
    marginBottom: 24,
  },
  sectionLabel: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 14,
    color: '#5A5546',
    marginBottom: 10,
  },
  byteSelector: {
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#D6D0C0',
    borderRadius: 999,
    padding: 4,
    marginBottom: 28,
  },
  byteOption: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  byteOptionSelected: {
    backgroundColor: '#F5F1E7',
  },
  byteOptionText: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 16,
    color: '#5A5546',
  },
  byteOptionTextSelected: {
    fontFamily: 'Newsreader_700Bold',
    color: '#2F2E2C',
  },
  deliveryRow: {
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#816148',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  deliveryRowLabel: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 16,
    color: '#F3EEE3',
  },
  deliveryRowValue: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 16,
    color: '#D9C9B3',
  },
  lockedRow: {
    width: '100%',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#B7AE9B',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  lockedRowText: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 14,
    color: '#5A5546',
  },
  topicRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  topicPill: {
    width: '48%',
    backgroundColor: '#D6D0C0',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicPillSelected: {
    backgroundColor: '#816148',
  },
  topicPillText: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 14,
    color: '#5A5546',
    textAlign: 'center',
  },
  topicPillTextSelected: {
    fontFamily: 'Newsreader_700Bold',
    color: '#F3EEE3',
  },
  notificationTop: {
    width: '100%',
  },
  notificationHeading: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 39,
    lineHeight: 45,
    color: '#2F2E2C',
    marginBottom: 14,
  },
  notificationSubheading: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 19,
    lineHeight: 27,
    color: '#5A5546',
    marginBottom: 32,
  },
  notificationCard: {
    width: '112%',
    alignSelf: 'center',
    aspectRatio: 660 / 232,
    marginBottom: 32,
  },
  notificationCaption: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 17,
    lineHeight: 25,
    color: '#5A5546',
    textAlign: 'center',
  },
  secondaryButton: {
    width: '100%',
    backgroundColor: 'transparent',
    borderRadius: 999,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#816148',
    marginTop: 12,
  },
  secondaryButtonPressed: {
    opacity: 0.6,
  },
  secondaryButtonText: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 17,
    color: '#816148',
  },

  // --- Sign up / auth form ---
  signUpScreen: {
    flex: 1,
    backgroundColor: '#E1DED3',
  },
  content: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 80,
  },
  signUpHeading: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 32,
    color: '#2F2E2C',
    marginBottom: 4,
  },
  signUpSubheading: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 18,
    color: '#5A5546',
    marginBottom: 32,
  },
  label: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 15,
    color: '#5A5546',
    marginBottom: 6,
    marginTop: 16,
  },
  input: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 17,
    color: '#2F2E2C',
    backgroundColor: '#F6F3EA',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#C6BDAB',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  error: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 15,
    color: '#B3261E',
    marginTop: 16,
  },
  passwordRow: {
    justifyContent: 'center',
  },
  passwordInput: {
    paddingRight: 44,
  },
  eyeButton: {
    position: 'absolute',
    right: 4,
    top: 0,
    bottom: 0,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    marginTop: 32,
    backgroundColor: '#816148',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPressed: {
    opacity: 0.7,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    fontFamily: 'Newsreader_700Bold',
    fontSize: 17,
    color: '#E1DED3',
  },
  signUpLinkText: {
    fontFamily: 'Newsreader_400Regular',
    fontSize: 15,
    color: '#816148',
    textDecorationLine: 'underline',
  },
});

export default styles;
